services:
  - type: web
    name: micro-image-cache
    runtime: node
    repo: https://github.com/veksen/micro-image.git
    plan: free
    buildCommand: yarn install; yarn build
    startCommand: yarn workspace micro-image-cache start
    envVars:
      - key: PORT
        value: 9999

  # A static site
  - type: web
    name: docs
    runtime: node
    plan: free
    buildCommand: yarn install; yarn build
    startCommand: yarn workspace @micro-image/docs start
    envVars:
      - key: PORT
        value: 10000
