services:
  - type: web
    name: micro-image-cache
    runtime: node
    repo: https://github.com/veksen/micro-image.git
    plan: free
    buildCommand: yarn workspace micro-image-cache install; yarn workspace micro-image-cache build
    startCommand: yarn workspace micro-image-cache start

  # A static site
  - type: web
    name: docs
    runtime: node
    plan: free
    buildCommand: yarn workspace @micro-image/docs install; yarn workspace @micro-image/docs build
    startCommand: yarn workspace @micro-image/docs start
